USE DATABASE DATA_QUALITY_DB;
USE SCHEMA DQ_CORE;
USE WAREHOUSE DQ_ANALYTICS_WH;


DESC TABLE DATA_QUALITY_DB.DQ_CONFIG.ENVIRONMENT_CONFIG;
DESC TABLE DATA_QUALITY_DB.DQ_CONFIG.DATASET_CONFIG;
DESC TABLE DATA_QUALITY_DB.DQ_CONFIG.DATASET_RULE_CONFIG;
DESC TABLE DATA_QUALITY_DB.DQ_CONFIG.RULE_MASTER;
DESC TABLE DATA_QUALITY_DB.DQ_CONFIG.RULE_SQL_TEMPLATE;

DESC TABLE DATA_QUALITY_DB.DQ_METRICS.DQ_RUN_CONTROL;
DESC TABLE DATA_QUALITY_DB.DQ_METRICS.DQ_CHECK_RESULTS;
DESC TABLE DATA_QUALITY_DB.DQ_METRICS.DQ_DAILY_SUMMARY;
DESC TABLE DATA_QUALITY_DB.DQ_METRICS.DQ_DOMAIN_DAILY_SUMMARY;
DESC TABLE DATA_QUALITY_DB.DQ_METRICS.DQ_RULE_TYPE_PERFORMANCE;
DESC TABLE DATA_QUALITY_DB.DQ_METRICS.DQ_COLUMN_QUALITY_PROFILE;





USE DATABASE DATA_QUALITY_DB;
USE SCHEMA DQ_CORE;

CALL SP_AGGREGATE_ALL_METRICS(
    (CURRENT_DATE - 300)::DATE,   -- P_START_DATE: last year
    (CURRENT_DATE + 300)::DATE,   -- P_END_DATE: next year
    NULL,                         -- P_DATASET_ID_FILTER
    NULL,                         -- P_BUSINESS_DOMAIN_FILTER
    TRUE                          -- P_FORCE_REFRESH
);









USE DATABASE DATA_QUALITY_DB;
USE SCHEMA DQ_CORE;

-- Trend
CALL SP_AGGREGATE_TREND_ANALYSIS(
    (CURRENT_DATE - 365)::DATE,
    (CURRENT_DATE + 365)::DATE,
    NULL,
    TRUE
);

-- Performance
CALL SP_AGGREGATE_PERFORMANCE_METRICS(
    (CURRENT_DATE - 365)::DATE,
    (CURRENT_DATE + 365)::DATE,
    NULL,
    TRUE
);

-- Cost
CALL SP_AGGREGATE_COST_METRICS(
    (CURRENT_DATE - 365)::DATE,
    (CURRENT_DATE + 365)::DATE,
    TRUE
);

-- Quarterly
CALL SP_AGGREGATE_QUARTERLY_METRICS(
    (CURRENT_DATE - 365)::DATE,
    (CURRENT_DATE + 365)::DATE,
    NULL,
    NULL,
    TRUE
);
