USE DATABASE BANKING_DW;
USE SCHEMA BRONZE;


CREATE OR REPLACE TABLE BANKING_DW.BRONZE.STG_CUSTOMER (
    customer_id      STRING      NOT NULL,
    customer_name    STRING,
    email            STRING,
    phone            STRING,
    dob              DATE,
    kyc_status       STRING,
    country          STRING,
    created_date     TIMESTAMP_NTZ,
    updated_date     TIMESTAMP_NTZ,
    source_system    STRING
);


CREATE OR REPLACE TABLE BANKING_DW.BRONZE.STG_ACCOUNT (
    account_id        STRING      NOT NULL,
    customer_id       STRING      NOT NULL,
    account_type      STRING,
    account_status    STRING,
    opening_balance   NUMBER(18,2),
    opened_date       DATE,
    currency_code     STRING,
    branch_code       STRING,
    created_date      TIMESTAMP_NTZ,
    updated_date      TIMESTAMP_NTZ
);


CREATE OR REPLACE TABLE BANKING_DW.BRONZE.STG_TRANSACTION (
    transaction_id      STRING      NOT NULL,
    account_id          STRING      NOT NULL,
    transaction_type    STRING,
    transaction_amount  NUMBER(18,2),
    transaction_date    TIMESTAMP_NTZ,
    currency_code       STRING,
    counterparty        STRING,
    channel             STRING,
    created_date        TIMESTAMP_NTZ,
    updated_date        TIMESTAMP_NTZ
);



CREATE OR REPLACE TABLE BANKING_DW.BRONZE.STG_DAILY_BALANCE (
    account_id       STRING      NOT NULL,
    balance_date     DATE        NOT NULL,
    closing_balance  NUMBER(18,2),
    currency_code    STRING,
    created_date     TIMESTAMP_NTZ,
    updated_date     TIMESTAMP_NTZ
);



CREATE OR REPLACE TABLE BANKING_DW.BRONZE.STG_FX_RATE (
    currency_code    STRING      NOT NULL,
    rate_date        DATE        NOT NULL,
    fx_rate_to_usd   NUMBER(18,8),
    source_system    STRING,
    created_date     TIMESTAMP_NTZ,
    updated_date     TIMESTAMP_NTZ
);






-- =======Loading the data ======


TRUNCATE TABLE BANKING_DW.BRONZE.STG_CUSTOMER;

INSERT INTO BANKING_DW.BRONZE.STG_CUSTOMER (
    customer_id, customer_name, email, phone, dob,
    kyc_status, country, created_date, updated_date, source_system
)
VALUES
  -- 1–10: mostly valid
  ('C001','Alice Sharma','alice.sharma@example.com','+91-9876543210','1990-05-10','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C002','Bob Singh','bob.singh@example.com','+91-9123456780','1985-11-20','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C003','Charlie Patel','charlie.patel@example.com','+91-9988776655','1992-03-15','Pending','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C004','Daisy Rao','daisy.rao@example.com','+91-9012345678','1995-07-22','Under Review','US',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C005','Emily Jain','emily.jain@example.com','+91-9876000001','1988-09-09','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C006','Farhan Khan','farhan.khan@example.com','+91-9876000002','1979-01-19','Verified','AE',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C007','Gaurav Joshi','gaurav.joshi@example.com','+91-9876000003','1991-12-30','Pending','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C008','Hema Iyer','hema.iyer@example.com','+91-9876000004','1983-04-11','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C009','Isha Kulkarni','isha.kulkarni@example.com','+91-9876000005','1994-02-17','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C010','John Doe','john.doe@example.com','+1-202-555-0100','1980-06-06','Verified','US',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),

  -- 11–20: completeness & format issues
  ('C011','Kiran Shah',NULL,'+91-9876000006','1993-03-03','Pending','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- missing email
  ('C012','Lakshmi Menon','lakshmi.menon[at]example.com','+91-9876000007','1992-10-10','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- bad email
  ('C013','Manoj Verma','manoj.verma@example.com',NULL,'1991-07-07','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- missing phone
  ('C014','Nidhi Gupta','nidhi.gupta@example.com','12345','1990-01-01','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- bad phone
  ('C015','Om Prakash','om.prakash@example.com','+91-9876000008',DATEADD(DAY,5,CURRENT_DATE()),'Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- future dob
  ('C016','Pooja Reddy','pooja.reddy@example.com','+91-9876000009','1870-01-01','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- very old dob (range)
  ('C017','Quentin Lee','quentin.lee@example.com','+44-20-7946-0958','1990-09-09','InvalidStatus','GB',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- bad kyc_status
  ('C018','Ravi Kumar','ravi.kumar@example.com','+91-9876000010','1993-08-08','Expired','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C019','Sara Thomas','sara.thomas@example.com','+91-9876000011','1987-11-11','Incomplete','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C020','Tarun Nair',NULL,NULL,NULL,'Pending',NULL,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- many NULLs

  -- 21–30: deliberate noise
  ('C021','User 21','user21@example.com','+91-9876000021','1991-01-21','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C022','User 22','user22@example','+91-9876000022','1992-02-22','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- bad email
  ('C023','User 23','user23@example.com','9876000023','1993-03-23','Verified','XX',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'), -- bad country code
  ('C024','User 24','user24@example.com','+91-9876000024',DATEADD(DAY,365,CURRENT_DATE()),'Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C025','User 25','user25@example.com','+91-9876000025','1995-05-25','Rejected','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C026','User 26','user26@example.com','+91-9876000026','1996-06-26','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C027','User 27','user27@example.com','+91-9876000027','1997-07-27','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C028','User 28','user28@example.com','+91-9876000028','1998-08-28','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C029','User 29','user29@example.com','+91-9876000029','1999-09-29','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING'),
  ('C030','User 30','user30@example.com','+91-9876000030','2000-10-30','Verified','IN',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'CORE_BANKING');






TRUNCATE TABLE BANKING_DW.BRONZE.STG_ACCOUNT;



INSERT INTO BANKING_DW.BRONZE.STG_ACCOUNT (
    account_id, customer_id, account_type, account_status,
    opening_balance, opened_date, currency_code, branch_code,
    created_date, updated_date
)
VALUES
  -- Valid accounts for C001–C010
  ('A001','C001','Savings','Active',10000.00,DATEADD(DAY,-90,CURRENT_DATE()),'INR','BR001',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A002','C002','Checking','Active',5000.00,DATEADD(DAY,-60,CURRENT_DATE()),'INR','BR001',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A003','C003','Savings','Inactive',2000.00,DATEADD(DAY,-30,CURRENT_DATE()),'INR','BR002',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A004','C004','Savings','Active',3000.00,DATEADD(DAY,-10,CURRENT_DATE()),'INR','BR003',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A005','C005','Credit','Active',-1000.00,DATEADD(DAY,-5,CURRENT_DATE()),'INR','BR003',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- negative balance
  ('A006','C006','Loan','Active',250000.00,DATEADD(DAY,-365,CURRENT_DATE()),'INR','BR004',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A007','C007','Savings','Dormant',1500.00,DATEADD(DAY,-730,CURRENT_DATE()),'INR','BR004',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A008','C008','Investment','Active',75000.00,DATEADD(DAY,-200,CURRENT_DATE()),'INR','BR005',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A009','C009','Savings','Frozen',300.00,DATEADD(DAY,-15,CURRENT_DATE()),'INR','BR005',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A010','C010','Checking','Closed',0.00,DATEADD(DAY,-1000,CURRENT_DATE()),'USD','BR001',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),

  -- 11–20: bad types/status, orphans
  ('A011','C011','INVALID_TYPE','Active',4000.00,DATEADD(DAY,-20,CURRENT_DATE()),'INR','BR002',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A012','C012','Savings','Dormantt',500.00,DATEADD(DAY,-50,CURRENT_DATE()),'INR','BR002',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A013','C013','Savings','Active',NULL,DATEADD(DAY,-10,CURRENT_DATE()),'INR','BR003',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- NULL opening_balance
  ('A014','C014','Savings','Active',100.00,DATEADD(DAY,-1,CURRENT_DATE()),'INR','BR003',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A015','C015','Checking','Active',800.00,DATEADD(DAY,-2,CURRENT_DATE()),'INR','BR003',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A016','C999','Savings','Active',200.00,DATEADD(DAY,-3,CURRENT_DATE()),'INR','BR004',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- orphan customer
  ('A017','C998','Loan','Active',50000.00,DATEADD(DAY,-4,CURRENT_DATE()),'INR','BR004',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- orphan
  ('A018','C018','Savings','Active',600.00,DATEADD(DAY,-5,CURRENT_DATE()),'INR','BR005',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A019','C019','Savings','Active',700.00,DATEADD(DAY,-6,CURRENT_DATE()),'INR','BR005',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A020','C020','Savings','Active',800.00,DATEADD(DAY,-7,CURRENT_DATE()),'INR','BR005',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),

  -- 21–30: mix of currencies, statuses
  ('A021','C021','Savings','Active',1000.00,DATEADD(DAY,-8,CURRENT_DATE()),'INR','BR006',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A022','C022','Savings','Active',1100.00,DATEADD(DAY,-9,CURRENT_DATE()),'INR','BR006',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A023','C023','Savings','Active',1200.00,DATEADD(DAY,-10,CURRENT_DATE()),'USD','BR006',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A024','C024','Savings','Active',1300.00,DATEADD(DAY,-11,CURRENT_DATE()),'INR','BR006',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A025','C025','Savings','Suspended',1400.00,DATEADD(DAY,-12,CURRENT_DATE()),'INR','BR006',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A026','C026','Money Market','Active',1500.00,DATEADD(DAY,-13,CURRENT_DATE()),'INR','BR007',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A027','C027','CD','Active',1600.00,DATEADD(DAY,-14,CURRENT_DATE()),'INR','BR007',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A028','C028','Savings','Active',1700.00,DATEADD(DAY,-15,CURRENT_DATE()),'INR','BR007',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A029','C029','Savings','Active',1800.00,DATEADD(DAY,-16,CURRENT_DATE()),'INR','BR007',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A030','C030','Savings','Active',1900.00,DATEADD(DAY,-17,CURRENT_DATE()),'XXX','BR007',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()); -- bad currency






TRUNCATE TABLE BANKING_DW.BRONZE.STG_TRANSACTION;


INSERT INTO BANKING_DW.BRONZE.STG_TRANSACTION (
    transaction_id, account_id, transaction_type,
    transaction_amount, transaction_date,
    currency_code, counterparty, channel,
    created_date, updated_date
)
VALUES
  -- Valid recent transactions for A001–A005
  ('T001','A001','Deposit',1500.00,DATEADD(HOUR,-1,CURRENT_TIMESTAMP()),'INR','CASH','ATM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T002','A001','Withdrawal',-500.00,DATEADD(HOUR,-2,CURRENT_TIMESTAMP()),'INR','CASH','ATM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T003','A002','Transfer',2000.00,DATEADD(HOUR,-3,CURRENT_TIMESTAMP()),'INR','C001','MOBILE',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T004','A002','Payment',750.00,DATEADD(HOUR,-4,CURRENT_TIMESTAMP()),'INR','MERCHANT1','CARD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T005','A003','Deposit',250.00,DATEADD(HOUR,-5,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T006','A004','Withdrawal',-300.00,DATEADD(HOUR,-6,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T007','A005','Fee',-50.00,DATEADD(HOUR,-7,CURRENT_TIMESTAMP()),'INR','BANK','SYSTEM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T008','A006','Interest',120.00,DATEADD(HOUR,-8,CURRENT_TIMESTAMP()),'INR','BANK','SYSTEM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T009','A007','Deposit',400.00,DATEADD(HOUR,-9,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T010','A008','Deposit',600.00,DATEADD(HOUR,-10,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),

  -- 11–20: NULLs, invalid types, orphans
  ('T011','A009','INVALID_TXN',100.00,DATEADD(HOUR,-11,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- bad type
  ('T012','A010','Deposit',NULL,DATEADD(HOUR,-12,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- NULL amount
  ('T013','A011','Payment',-9999999.99,DATEADD(HOUR,-13,CURRENT_TIMESTAMP()),'INR','MERCHANT2','CARD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- huge negative
  ('T014','A012','Deposit',100.00,DATEADD(DAY,2,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- future date
  ('T015','A013','Deposit',200.00,DATEADD(DAY,-30,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T016','A014','Transfer',300.00,DATEADD(DAY,-1,CURRENT_TIMESTAMP()),'INR','C002','MOBILE',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T017','A015','Payment',400.00,DATEADD(DAY,-2,CURRENT_TIMESTAMP()),'INR','MERCHANT3','CARD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T018','A016','Deposit',500.00,DATEADD(DAY,-3,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- orphan account
  ('T019','AXXX','Deposit',600.00,DATEADD(DAY,-4,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- orphan
  ('T020','A001','Fee',-25.00,DATEADD(DAY,-5,CURRENT_TIMESTAMP()),'INR','BANK','SYSTEM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),

  -- 21–40: mix of currencies, noise
  ('T021','A017','Deposit',100.00,DATEADD(HOUR,-1,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T022','A018','Withdrawal',-80.00,DATEADD(HOUR,-2,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T023','A019','Payment',150.00,DATEADD(HOUR,-3,CURRENT_TIMESTAMP()),'INR','MERCHANT4','CARD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T024','A020','Transfer',200.00,DATEADD(HOUR,-4,CURRENT_TIMESTAMP()),'INR','C003','MOBILE',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T025','A021','Deposit',120.00,DATEADD(HOUR,-5,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T026','A022','Deposit',130.00,DATEADD(HOUR,-6,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T027','A023','Deposit',140.00,DATEADD(HOUR,-7,CURRENT_TIMESTAMP()),'USD','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T028','A024','Deposit',150.00,DATEADD(HOUR,-8,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T029','A025','Deposit',160.00,DATEADD(HOUR,-9,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T030','A026','Deposit',170.00,DATEADD(HOUR,-10,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T031','A027','Deposit',180.00,DATEADD(HOUR,-11,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T032','A028','Deposit',190.00,DATEADD(HOUR,-12,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T033','A029','Deposit',200.00,DATEADD(HOUR,-13,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T034','A030','Deposit',210.00,DATEADD(HOUR,-14,CURRENT_TIMESTAMP()),'XXX','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- bad currency
  ('T035','A001','Deposit',NULL,DATEADD(HOUR,-15,CURRENT_TIMESTAMP()),'INR','CASH','ATM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T036','A002','INVALID_TXN',50.00,DATEADD(HOUR,-16,CURRENT_TIMESTAMP()),'INR','CASH','ATM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T037','A003','Fee',-5.00,DATEADD(HOUR,-17,CURRENT_TIMESTAMP()),'INR','BANK','SYSTEM',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T038','A004','Deposit',1000000.00,DATEADD(HOUR,-18,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T039','A005','Deposit',50.00,DATEADD(HOUR,-19,CURRENT_TIMESTAMP()),'INR','CASH','BRANCH',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('T040','A006','Payment',-70.00,DATEADD(HOUR,-20,CURRENT_TIMESTAMP()),'INR','MERCHANT5','CARD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());





TRUNCATE TABLE BANKING_DW.BRONZE.STG_DAILY_BALANCE;



INSERT INTO BANKING_DW.BRONZE.STG_DAILY_BALANCE (
    account_id, balance_date, closing_balance,
    currency_code, created_date, updated_date
)
VALUES
  -- balances today for many accounts
  ('A001',CURRENT_DATE(),11000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A002',CURRENT_DATE(),7000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A003',CURRENT_DATE(),2100.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A004',CURRENT_DATE(),2600.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A005',CURRENT_DATE(),-900.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- negative
  ('A006',CURRENT_DATE(),255000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A007',CURRENT_DATE(),1900.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A008',CURRENT_DATE(),76000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A009',CURRENT_DATE(),350.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A010',CURRENT_DATE(),0.00,'USD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),

  -- gaps, NULLs, orphans
  ('A011',CURRENT_DATE(),4000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A012',CURRENT_DATE(),500.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A013',CURRENT_DATE(),NULL,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- null
  ('A014',CURRENT_DATE(),100.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A015',CURRENT_DATE(),800.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A016',CURRENT_DATE(),200.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A017',CURRENT_DATE(),50000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A018',CURRENT_DATE(),600.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A019',CURRENT_DATE(),700.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A020',CURRENT_DATE(),800.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),

  -- extra + orphan
  ('A021',CURRENT_DATE(),1000.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A022',CURRENT_DATE(),1100.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A023',CURRENT_DATE(),1200.00,'USD',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A024',CURRENT_DATE(),1300.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A025',CURRENT_DATE(),1400.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A026',CURRENT_DATE(),1500.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A027',CURRENT_DATE(),1600.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A028',CURRENT_DATE(),1700.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A029',CURRENT_DATE(),1800.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('A999',CURRENT_DATE(),500.00,'INR',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()); -- orphan






TRUNCATE TABLE BANKING_DW.BRONZE.STG_FX_RATE;


INSERT INTO BANKING_DW.BRONZE.STG_FX_RATE (
    currency_code, rate_date, fx_rate_to_usd,
    source_system, created_date, updated_date
)
VALUES
  ('INR',CURRENT_DATE(),0.012,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('USD',CURRENT_DATE(),1.000,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('EUR',CURRENT_DATE(),1.10,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('GBP',CURRENT_DATE(),1.25,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('JPY',CURRENT_DATE(),0.009,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('AUD',CURRENT_DATE(),0.65,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('CAD',CURRENT_DATE(),0.75,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('CHF',CURRENT_DATE(),1.05,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('MXN',CURRENT_DATE(),0.055,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('BRL',CURRENT_DATE(),0.20,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  -- some older dates
  ('INR',DATEADD(DAY,-1,CURRENT_DATE()),0.0121,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('EUR',DATEADD(DAY,-1,CURRENT_DATE()),1.11,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  -- faulty rows
  ('XXX',CURRENT_DATE(),-0.5,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- bad code + negative
  ('ABC',CURRENT_DATE(),NULL,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()), -- null rate
  ('INR',DATEADD(DAY,-10,CURRENT_DATE()),0.011,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('USD',DATEADD(DAY,-10,CURRENT_DATE()),1.000,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('EUR',DATEADD(DAY,-10,CURRENT_DATE()),1.09,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('GBP',DATEADD(DAY,-10,CURRENT_DATE()),1.23,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('JPY',DATEADD(DAY,-10,CURRENT_DATE()),0.0091,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('AUD',DATEADD(DAY,-10,CURRENT_DATE()),0.64,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('CAD',DATEADD(DAY,-10,CURRENT_DATE()),0.74,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('CHF',DATEADD(DAY,-10,CURRENT_DATE()),1.04,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('MXN',DATEADD(DAY,-10,CURRENT_DATE()),0.054,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()),
  ('BRL',DATEADD(DAY,-10,CURRENT_DATE()),0.19,'REUTERS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());



